build: import "gl" dependency
[    3s] ../lib/SRMBuffer.c:1:10: fatal error: GL/gl.h: No such file or directory

Looking for the GLESv2 component is not enough to ensure gl.h exists.
The Mesa packages considers them to be separate entities (because different
.pc files), and distributions readily split Mesa into individually-installable
libGL and libGLESv2 components, too.